overrides:
  vite: npm:rolldown-vite@latest

catalogs:
  build:
    '@nuxt/devtools': ^3.1.0
    '@nuxt/eslint': ^1.10.0
    '@nuxt/image': ^2.0.0
    '@nuxt/kit': ^4.2.1
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.5.5
    '@unocss/nuxt': ^66.5.5
    '@vite-pwa/nuxt': ^1.0.7
    '@vueuse/nuxt': ^14.0.0
    nuxt: ^4.2.1
    reka-ui: ^2.6.0
    unocss: ^66.5.5
    unplugin: ^2.3.10
    vite: npm:rolldown-vite@latest
  dev:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
    eslint-plugin-format: ^1.0.2
    eslint-plugin-oxlint: ^1.26.0
    typescript: ^5.9.3
    vue-tsc: ^3.1.3
  frontend:
    '@vueuse/core': ^14.0.0
    pinia: ^3.0.4
    vue: ^3.5.24
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/lucide': ^1.2.73
    '@iconify-json/lucide-lab': ^1.2.3
    '@iconify-json/material-symbols': ^1.2.45
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

package: []
